#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/Doors.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/joda-time-2.1-javadoc.jar:$APPDIR/lib/joda-time-2.1.jar:$APPDIR/lib/nrserial.jar:$APPDIR/lib/PixelPusher.jar" Doors "$@"
